# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sri Lanka Federation of Youth Clubs
# email: nir3al+youthlk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official website of Lanka Youth Federation
baseurl: "" # the subpath of your site, e.g. /blog

domain: "http://localhost:4000"
# domain: "http://youthlk.github.com"

disqus_id: "youthlk"

url: "http://youthlk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_url: https://facebook.com/nirmallankathilaka
twitter_url: https://twitter.com/srdyel
email: nir3al+youthlk@gmail.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  include: ['_pages']
  # style: compressed
kramdown:
  input: GFM
  highlighter: pygments